name: Build oee-simulators

on:
  workflow_call:
    inputs:
      release_body:
        type: string
        required: true

jobs:
  build-upload:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ env.RELEASE_VERSION }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'repo'

      - name: Set branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Update version number
        run: |
          cd repo/simulators
          SIMULATOR_VERSION=${GITHUB_RUN_NUMBER}
          sed -i "s/@project.version@/1.0.${SIMULATOR_VERSION}/g" cumulocity.json
          echo "RELEASE_VERSION=${SIMULATOR_VERSION}" >> $GITHUB_ENV
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - name: Build Docker image
        run: |
          cd repo/simulators
          docker build -t oee-simulators .
          docker save -o image.tar oee-simulators
          docker rmi oee-simulators

      - name: Upload file and zip an artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: 'oee-simulators'
          path: |
            repo/simulators/image.tar
            repo/simulators/cumulocity.json
        id: upload-artifact

  call-release-workflow:
    needs: build-upload
    uses: ./.github/workflows/release.yml
    with:
      RELEASE_VERSION: ${{ needs.build-upload.outputs.release_version }}
      release_body: ${{ inputs.release_body }}
