# Build docker image, build cumulocity archive and release it to the repository

name: Build oee-simulators

on:
  workflow_dispatch:
    inputs:
        release_body:
          type: string
          description: GitHub Build Message
          default: "GitHub Build Message"

env:
  BUILD_OFFSET: 20

jobs:
  build_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'repo'

      - name: update versionnumber
        run: |
          cd repo/simulators
          SIMULATOR_VERSION=$(expr ${{ env.BUILD_OFFSET }} + ${GITHUB_RUN_NUMBER})
          sed -i "s/@project.version@/1.0.${SIMULATOR_VERSION}/g" cumulocity.json
          echo "RELEASE_VERSION=${SIMULATOR_VERSION}" >> $GITHUB_ENV

      - name: Zip the source-code
        run: |
          zip -r source-code.zip repo

      - name: build docker image
        run: |
          cd repo/simulators
          docker build -t oee-simulators .
          docker save -o image.tar oee-simulators
          docker rmi oee-simulators

      - name: Zip it!
        run: |
          cd repo/simulators
          zip oee-simulators.zip image.tar cumulocity.json
        
      - name: upload Zip
        uses: actions/upload-artifact@v3.1.1
        with:
          name: 'oee-simulators'
          path: 'repo/simulators/oee-simulators.zip'

  create-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/release.yml