name: Build oee-simulators

on:
  workflow_call:

jobs:
  build_upload:
    runs-on: ubuntu-latest
    if: github.event.inputs.trigger == 'true'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'repo'

      - name: Update version number
        run: |
          cd repo/simulators
          SIMULATOR_VERSION=${GITHUB_RUN_NUMBER}
          sed -i "s/@project.version@/1.0.${SIMULATOR_VERSION}/g" cumulocity.json
          echo "RELEASE_VERSION=${SIMULATOR_VERSION}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          cd repo/sims
          docker build -t oee-simulators .
          docker save -o image.tar oee-simulators
          docker rmi oee-simulators

      - name: upload file and zip an artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: 'oee-simulators'
          path: |
            repo/simulators/image.tar
            repo/simulators/cumulocity.json

  call-workflow:
    uses: .github/workflows/release.yml@${{ env.BRANCH_NAME }}
