# Build docker image, build cumulocity archive and release it to the repository

name: Build & release oee-simulators

on:
  workflow_dispatch:
    inputs:
        release_body:
          type: string
          description: GitHub Release Message
          default: "GitHub Release Message"

env:
  BUILD_OFFSET: 20

jobs:
  build_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'repo'

      - name: update versionnumber
        run: |
          cd repo/simulators
          SIMULATOR_VERSION=$(expr ${{ env.BUILD_OFFSET }} + ${GITHUB_RUN_NUMBER})
          sed -i "s/@project.version@/1.0.${SIMULATOR_VERSION}/g" cumulocity.json
          echo "RELEASE_VERSION=${SIMULATOR_VERSION}" >> $GITHUB_ENV

      - name: Zip the source-code
        run: |
          zip -r source-code.zip repo

      - name: build docker image
        run: |
          cd repo/simulators
          docker build -t oee-simulators .
          docker save -o image.tar oee-simulators
          docker rmi oee-simulators

      - name: Zip it!
        run: |
          cd repo/simulators
          zip oee-simulators.zip image.tar cumulocity.json
        
      - name: upload Zip
        uses: actions/upload-artifact@v3.1.1
        with:
          name: 'oee-simulators'
          path: 'repo/simulators/oee-simulators.zip'

  create-release:
    runs-on: ubuntu-latest
    if: github.repository == 'main'
    steps:
      - name: Create Release
        uses: actions/create-release@v1.1.4
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v1.0.${{ env.RELEASE_VERSION }}
          tag_name: v1.0.${{ env.RELEASE_VERSION }}
          body: ${{ github.event.inputs.release_body }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload oee-sim zip
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'repo/simulators/oee-simulators.zip'
          asset_name: 'oee-simulators.zip'
          asset_content_type: application/zip

      - name: upload source-code zip
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'source-code.zip'
          asset_name: 'oee-simulators-src.zip'
          asset_content_type: application/zip