# Build docker image, build cumulocity archive and release it to the repository

name: Release oee-simulators

on:
  workflow_call:
    inputs:
        release_body:
          type: string
          description: GitHub Release Message
          default: "GitHub Release Message"

env:
  BUILD_OFFSET: 20

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Create Release
        uses: actions/create-release@v1.1.4
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v1.0.${{ env.RELEASE_VERSION }}
          tag_name: v1.0.${{ env.RELEASE_VERSION }}
          body: ${{ github.event.inputs.release_body }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload oee-sim zip
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'repo/simulators/oee-simulators.zip'
          asset_name: 'oee-simulators.zip'
          asset_content_type: application/zip

      - name: upload source-code zip
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'source-code.zip'
          asset_name: 'oee-simulators-src.zip'
          asset_content_type: application/zip