# Release public oee-simulators

name: Release oee-simulators

on:
  workflow_dispatch:
    inputs:
      release_body:
        type: string
        description: GitHub Release Message
        default: "Release version ${{ github.run_number }}"

      environment:
        type: environment
        description: Name of the environment to use
        default: "oee-dev"
        required: true

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      C8Y_PASSWORD: ${{ secrets.C8Y_PASSWORD }}

  build-release:
    if: github.ref == 'refs/heads/main'
    needs: call-build-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'repo'

      - name: Zip files for release
        run: |
          cd repo/simulators
          zip oee-simulators.zip image.tar cumulocity.json

      - name: Create Release
        uses: actions/create-release@v1.1.4
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v1.0.$${{ needs.call-build-workflow.outputs.release_version }}
          tag_name: v1.0.${{ needs.call-build-workflow.outputs.release_version }}
          body: ${{ inputs.release_body }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload oee-sim zip
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # upload_url output is provided automatically by the GitHub API when the release is created
          asset_path: 'repo/simulators/oee-simulators.zip'
          asset_name: 'oee-simulators.zip'
          asset_content_type: application/zip