# Release public oee-simulators

name: Release oee-simulators

on:
  push:
    branches:
      - main
    # Only run the workflow when build.yml has completed successfully
    paths-ignore:
      - '**'
    # Wait for the build job to complete before running the release job
    jobs:
      - build

jobs:
  build_upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'repo'

      - name: Zip the source-code
        run: |
          cd repo/simulators
          zip -r source-code.zip .

      - name: Zip files for release
        run: |
          cd repo/simulators
          zip oee-simulators.zip image.tar cumulocity.json

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: actions/create-release@v1.1.4
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v1.0.${{ env.RELEASE_VERSION }}
          tag_name: v1.0.${{ env.RELEASE_VERSION }}
          body: ${{ github.event.inputs.release_body }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload oee-sim zip
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'repo/simulators/oee-simulators.zip'
          asset_name: 'oee-simulators.zip'
          asset_content_type: application/zip

      - name: upload source-code zip
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'source-code.zip'
          asset_name: 'oee-simulators-src.zip'
          asset_content_type: application/zip
