name: Run tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Name of the environment to use
        default: "oee-dev"
        options:
          oee-dev: oee-dev Environment
        required: true
      release_body:
        type: string
        description: GitHub Release Message
        default: "GitHub Manual Release"

  push:
    branches: [ '*' ]
    environment:
      name: oee-dev

env:
  C8Y_PASSWORD: ${{ secrets.C8Y_PASSWORD }}
  C8Y_BASEURL: ${{ vars.C8Y_BASEURL }}
  C8Y_TENANT: ${{ vars.C8Y_TENANT }}
  C8Y_USER: ${{ vars.C8Y_USER }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: ${{ github.event.deployment.environment || github.event.inputs.environment }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'repo'

      - name: Check Environment
        run:
          echo "Running on environment ${{ github.event.deployment.environment || github.event.inputs.environment }}"

      - name: Run tests
        run: |
          cd repo
          python test/simulators_test.py
          pip3 install c8y-api
          python test/export_import_test.py
        env:
          C8Y_BASEURL: ${{ env.C8Y_BASEURL }}
          C8Y_PASSWORD: ${{ env.C8Y_PASSWORD }}
          C8Y_TENANT: ${{ env.C8Y_TENANT }}
          C8Y_USER: ${{ env.C8Y_USER }}

  call-build-workflow:
    needs: run-tests
    uses: ./.github/workflows/build.yml
    with:
      release_body: ${{ github.event.inputs.release_body || 'Test' }} # Add Test string as placeholder to avoid error
