name: Run tests

on:
  push:
    branches: ['*']

  workflow_dispatch:
    inputs:
      release_body:
        type: string
        description: Manual workflow run
        default: "Manual workflow run"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'repo'

      - name: Run tests
        run: |
          cd repo
          python -m unittest discover -s test -p "*_test.py" -v

  call-build-workflow:
    uses: ./.github/workflows/build.yml
