name: Run tests

on:
  push:
    branches: ['*']

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'repo'

      - name: Run tests
        run: |
          python -m unittest discover -s test -p "*_test.py"

  call-build-workflow:
    uses: ./.github/workflows/build.yml
    with:
      trigger: 'build'