name: Run tests

on:
  workflow_dispatch:
    inputs:
      release_body:
        type: string
        description: Manual workflow run
        default: "Manual workflow run"
  push:
    branches: [ '*' ]

env:
  C8Y_BASEURL: ${{ secrets.C8Y_BASEURL }}
  C8Y_PASSWORD: ${{ secrets.C8Y_PASSWORD }}
  C8Y_TENANT: ${{ secrets.C8Y_TENANT }}
  C8Y_USER: ${{ secrets.C8Y_USER }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: Nam
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'repo'

      - name: Run tests
        run: |
          cd repo
          python -m unittest discover -s test -p "*_test.py" -v
        env:
          C8Y_BASEURL: ${{ env.C8Y_BASEURL }}
          C8Y_PASSWORD: ${{ env.C8Y_PASSWORD }}
          C8Y_TENANT: ${{ env.C8Y_TENANT }}
          C8Y_USER: ${{ env.C8Y_USER }}

  call-build-workflow:
    needs: run-tests
    uses: ./.github/workflows/build.yml
